### ISSUE TITLE
Does not work!

### ISSUE THREAD

**Issue by mailanetworks** [aravindavk/gdash#2]
The spinning wheel keeps ongoing...

----
[root@cluster01 ~]# GLUSTER_BIN_PATH=$(which gluster)
[root@cluster01 ~]# gdash --debug --gluster $GLUSTER_BIN_PATH
 * Running on http://0.0.0.0:8080/
 * Restarting with reloader
172.31.10.203 - - [07/Jan/2015 15:07:17] "GET / HTTP/1.1" 200 -
172.31.10.203 - - [07/Jan/2015 15:07:17] "GET /data HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.6/site-packages/gdash/app.py", line 90, in get_data
    result = json.dumps(parse(clusters, args))
  File "/usr/lib/python2.6/site-packages/gdash/cliparser.py", line 218, in parse
    volumes += get_volumes(cluster_name, hosts, args)
  File "/usr/lib/python2.6/site-packages/gdash/cliparser.py", line 195, in get_volumes
    vols = get_vol_info(cluster_name, hosts, args)
  File "/usr/lib/python2.6/site-packages/gdash/cliparser.py", line 176, in get_vol_info
    return get_vol_info_from_host(cluster_name, host, args)
  File "/usr/lib/python2.6/site-packages/gdash/cliparser.py", line 146, in get_vol_info_from_host
    raise GlusterBadXmlFormat(str(e))
GlusterBadXmlFormat: 'NoneType' object has no attribute 'text'
---

**Comment by aravindavk** [comment]
Looks like you are using old glusterfs, let me fix the xml parsing of gluster cli output. Thanks for reporting.

**Comment by mailanetworks** [comment]
3.4.1 to be more specific.
I'll upgrade to 3.5.3 tonight and report back. 
Thanks,

**Comment by mailanetworks** [comment]
Nicely done, worked like a charm after the update.
Many thanks for the nice product.
Do you plan to add new features?

Best regards,
